FROM python:alpine3.10
WORKDIR /
COPY . /
RUN pip install -r requirements.txt
EXPOSE 8080
CMD python ./backend/main.py

#COPY requirements.txt /app/requirements.txt
#ENTRYPOINT ["python", "./backend/main.py"]
# docker build -t dmaharajanm/helloworld-pythonapp .
# docker run -d -p 5000:5000 --name=helloworld-pythonapp dmaharajanm/helloworld-pythonapp